module(load="imtcp")
input(type="imtcp" port="514")

template(name="SISL" 
         type="string"
         string="{pri: !int \"%pri%\", timestamp: !int \"%TIMESTAMP:::date-unixtimestamp%\", hostname: !str \"%hostname%\", syslogtag: !str \"%syslogtag%\", msg: !str \"%msg%\"}")

module(load="omprog")
action(type="omprog"
       useTransactions="on"
       template="SISL"
       binary="/usr/bin/omtftp tftp://imtftp:69/irrelevant"
       output="/dev/stdout")

action(type="omfile" file="/dev/stdout")
