name: on_commit

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: build
        run: ./dev/run_in_pod.sh "just build"

      - name: package amd64
        run: ./dev/run_in_pod.sh "just package"

      - name: package arm64
        run: ./dev/run_in_pod.sh "just package arm64"

      - name: release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: build/*.deb