name: on_commit

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: lint
        run: ./dev/run_in_pod.sh "just e2e-lint"

      - name: test
        run: ./dev/run_in_pod.sh "just test"

      - name: package
        run: ./dev/run_in_pod.sh "just package-all"

      - name: release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            build/*.deb
            build/*.rpm